load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
RULES_JVM_EXTERNAL_TAG = "3.3"
RULES_JVM_EXTERNAL_SHA = "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "jakarta.validation:jakarta.validation-api:3.0.0",
        "javax.validation:validation-api:2.0.0.Final",
        "javax.ws.rs:javax.ws.rs-api:2.1.1",
        "org.hibernate.validator:hibernate-validator:6.1.7.Final",
        "com.fasterxml.jackson.core:jackson-annotations:2.12.0",
        "com.google.guava:guava:30.1-jre",
        "io.dropwizard.metrics:metrics-annotation:4.1.16",
        "io.dropwizard:dropwizard-dependencies:2.0.0",
        "io.dropwizard:dropwizard-core:2.0.0",
    ],
    fetch_sources = True,
    repositories = [
        "https://jcenter.bintray.com/",
        "https://repo1.maven.org/maven2",
    ],
)
